name: dooc_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  win32: ^5.1.0
  cupertino_icons: ^1.0.2
  #Flutter Widgets that make it easy to implement the BLoC (Business Logic
  flutter_bloc: ^8.1.3
  #Code generation(used mainly with cubit &API service) for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  #for Dependencies injection
  get_it: ^7.6.4
  #Classes and helper functions that support JSON code generation
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  #A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.7
  #Networking
  #A powerful HTTP networking package, supports Interceptors, Aborting and canceling a request, Custom adapters, Transformers, etc
  dio: ^5.4.0
  #retrofit.dart is an dio client generator
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.6
  #Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.4.0
  equatable: ^2.0.5
  #Easy and Fast internationalizing and localization your Flutter Apps
  #Contains code to deal with internationalized/localized messages, date and number formatting and parsing
  intl: ^0.19.0
  easy_localization: ^3.0.7
  flutter_localizations:
    sdk: flutter
  #An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.9
  #A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.0

  flutter_native_splash: ^2.3.8
  dartz: ^0.10.1
  fluttertoast: ^8.2.8
  flutter_pw_validator: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
    - assets/svgs/

  uses-material-design: true


